Add data to Snoozed/Approved/Rejected tabs
Pocket/curation-tools-frontend pull request #119
Opened 2021-02-07 09:24 UTC by nina-py

- Updated Prospects page to load data on all four tabs.

- Updated Tab component to always render the chip for number of articles, but show a loading spinner while the API call is in progress so that renders and re-renders do not cause content to jump around on the page.

- Updated data generation script for the local API (snoozedUntil field is now a timestamp).

Note that I haven't updated tests for the Prospects page as there is unexpected (!) trickiness around testing custom hooks. There should be ways to increase test coverage, but for now the new calls to the local API are untested. Please note that some of the data has been changed so before testing the PR locally, you need to rerun `npm run api:generate-data` script.

2021-02-08 14:05 UTC, kkyeboah requested changes
Nice  work so far. I have a few comments after running this locally:
- The snoozed tab "chip" apears to be the only one reloading when you navigate to any tab.
- All the cards are the same. I'm ok with this if you are aware and planned to address in another PR so this one is not bloated.
- When you hit any action i.e. "Snooze" or "Reject", the URL changes briefly in the URL bar. I don't think this is a big deal but it's something I noticed.
- Unrelated to this PR but buttons need a little margin from the tabs in the nav. See below
![Screen Shot 2021-02-08 at 9 03 08 AM](https://user-images.githubusercontent.com/10347996/107229980-79b47500-69ec-11eb-8368-9629bbc77eb7.png)
- Could we apply the same font to the locale?
![Screen Shot 2021-02-08 at 9 04 35 AM](https://user-images.githubusercontent.com/10347996/107230144-ad8f9a80-69ec-11eb-976e-5d86fafbb8ef.png)

2021-02-08 20:24 UTC, nina-py commented
@kkyeboah, the tabs re-render as you go from one tab to another. The data on the page is fetched from Apollo cache, but it seems on the dev version at least that a slightly more complex query like the snoozed one gets parsed noticeably slower compared to the other three. I've checked and double-checked the code and this is the only difference. 

Yes, I've deliberately kept the cards as-is. Was planning a separate PR for this & wanted to bundle mobile-friendly updates into cards as well, but can do it in this PR. 

I haven't noticed the URL change but it's interesting! There shouldn't be anything there that would cause this.

The header - yes, that component needs rewriting from scratch. I've already got a branch for this and have been working on it between other things.

2021-02-09 15:05 UTC, kkyeboah commented
@nina-py that's interesting concerning data for snoozed taking longer.
- I'm ok with a follow up to address the cards
- About the header, I'd say let's get everything wired up to make this functional before we spend time on UI touchups.

I'll approve this to unblock the follow-up work.

2021-02-09 15:05 UTC, kkyeboah approved these changes

2021-02-09 15:05 UTC, merged