worked on the login form--#issue 68
Pocket/curation-tools-frontend pull request #74
Opened 2020-10-23 03:47 UTC by alicendeh

## Goal

Insert purpose of pull request

## Todos:
- [ ] Outstanding todo
- [x] Completed todo
 
## Implementation Decisions

2020-10-23 08:56 UTC, alicendeh commented
Sorry it’s issue 65

2020-10-23 17:48 UTC, kkyeboah requested changes
This is a great start, just a couple of comments for improvement. Good job so far.

2020-10-23 17:48 UTC, kkyeboah commented on src/components/LoginForm.tsx
> +        <TextField
Could you change this to a password field? 

Also, there is some alignment issue with the password text field. See screenshot below:
![Screen Shot 2020-10-23 at 1 44 50 PM](https://user-images.githubusercontent.com/10347996/97036567-03bbf900-1536-11eb-8883-593326c842ef.png)

2020-10-23 17:48 UTC, kkyeboah commented on src/components/LoginForm.tsx
> +        <img src={logo} alt='Pockets Logo' className={classes.img} />
Could you adjust the logo position to be centered? Please refer to the screenshot in the issue.

![Screen Shot 2020-10-23 at 1 45 46 PM](https://user-images.githubusercontent.com/10347996/97036653-24844e80-1536-11eb-8e39-60d3f5aa57bb.png)

2020-10-25 05:11 UTC, alicendeh commented
I have made the required changes based on @kkyeboah  review

2020-10-25 18:51 UTC, alicendeh commented
Hi Mentor Kelvin I’ve done the corrections you asked for on the login component 
While you review that issue, please I’d like to know if am permitted to work on this one https://github.com/Pocket/curation-tools-frontend/issues/70

Sent from my iPhone

> On Oct 23, 2020, at 18:49, Kelvin Yeboah <notifications@github.com> wrote:
> 
> ﻿
> @kkyeboah requested changes on this pull request.
> 
> This is a great start, just a couple of comments for improvement. Good job so far.
> 
> In src/components/LoginForm.tsx:
> 
> > +      textTransform: 'capitalize',
> +    },
> +    input: {
> +      marginTop: '2em',
> +      paddingTop: '1em',
> +    },
> +  })
> +);
> +const LoginForm: React.FC = () => {
> +  const classes = useStyles();
> +  return (
> +    <div>
> +      <form noValidate autoComplete='off' className={classes.form}>
> +        <img src={logo} alt='Pockets Logo' className={classes.img} />
> +        <TextField id='outlined-basic' label='Your Email' variant='outlined' />
> +        <TextField
> Could you change this to a password field?
> 
> Also, there is some alignment issue with the password text field. See screenshot below:
> 
> 
> In src/components/LoginForm.tsx:
> 
> > +      color: 'white',
> +      margin: '1.5em auto',
> +      textTransform: 'capitalize',
> +    },
> +    input: {
> +      marginTop: '2em',
> +      paddingTop: '1em',
> +    },
> +  })
> +);
> +const LoginForm: React.FC = () => {
> +  const classes = useStyles();
> +  return (
> +    <div>
> +      <form noValidate autoComplete='off' className={classes.form}>
> +        <img src={logo} alt='Pockets Logo' className={classes.img} />
> Could you adjust the logo position to be centered? Please refer to the screenshot in the issue.
> 
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-26 16:19 UTC, kkyeboah submitted a review, later dismissed
This looks good to us 👍 Nice work.

Please revert your changes to `App.tsx` and we'll be happy to re-approve and merge your PR

2020-10-28 10:52 UTC, alicendeh commented
Hi @kkyeboah  I have reverted the change already

2020-10-28 16:23 UTC, kkyeboah requested changes
@alicendeh Please make sure `App.tsx` is not part of your PR changes.

2020-10-29 07:43 UTC, alicendeh commented
I've reverted as requested is this okay to be merged
 @kkyeboah

2020-10-29 10:55 UTC, nina-py commented
Hey @alicendeh , if you click over to the "Files changed" tab (https://github.com/Pocket/curation-tools-frontend/pull/74/files), you will see that the App.tsx file is still present in your commit with just one missing space! I know it's frustrating, but you're almost there.

Once you make one last commit to take care of that, you could also tidy up the commit history in your branch by squashing the last several commits that address the same thing - reverting the changes to App.tsx. Squashing commits is, in effect, rewriting the commit history for the branch so that there is just one commit reverting the changes instead of several. There is a good guide on how to do that here: https://github.com/wprig/wprig/wiki/How-to-squash-commits.

If `git rebase -i main` doesn't work for you, try `git rebase -i HEAD~6`. The number six here is the number of commits you want to squash. The actual changes you have made to the files in those several commits will still be there.

2020-10-29 12:03 UTC, alicendeh commented
Hi @nina-py  the problem am facing is that when I try reverting, it’s not going

2020-10-29 12:15 UTC, nina-py commented
Don't revert then, simply do another commit. Look at the diff of App.tsx in
the "Files changed" tab - there is one missing space in the front of the
comment (highlighted in pink) and one extra space at the end of it
(highlighted in green). Fix that on your branch, commit and push your
changes, then open the "Files changed" tab on your pull request again to
make sure App.tsx has dropped off the list of files you changed.

On Thu, 29 Oct 2020, 23:03 alicendeh, <notifications@github.com> wrote:

> Hi @nina-py <https://github.com/nina-py> the problem am facing is that
> when I try reverting, it’s not going
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Pocket/curation-tools-frontend/pull/74#issuecomment-718708500>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFLINKMSQMAPLSRQFHJOHMTSNFK2LANCNFSM4S4AXIFQ>
> .
>

2020-10-30 11:44 UTC, closed without merging