Issue 66 add story page component
Pocket/curation-tools-frontend pull request #75
Opened 2020-10-23 15:32 UTC by mhtien

## Goal

Create Add Story Page Component

## Todos:
- [ ] Outstanding todo
- [x] Completed todo
 
## Implementation Decisions

2020-10-23 17:56 UTC, kkyeboah requested changes
This looks great but we have a few comments:

Could you please make sure that your PR only contains changes for your component?

2020-10-23 17:56 UTC, kkyeboah commented on src/components/AddStory.tsx
> +        <TextField className="url-input"
Could you also make the text in this text field a placeholder so you don't have to delete the text before adding your own URL?

2020-10-23 21:40 UTC, mhtien commented
Hi @kkyeboah,

Comments noted, I opened up another pull request #76 that just includes the component, and the input field has a placeholder now.

Let me know if you have any more comments thanks!

2020-10-26 16:25 UTC, jpetto commented
closing in favor of #76

2020-10-26 16:25 UTC, closed without merging