Added a CardText component
Pocket/curation-tools-frontend pull request #77
Opened 2020-10-24 02:09 UTC by nina-py

## Goal

This component renders a block that is meant to go inside the Card component (#62) with the following properties:

- Title
- URL
- Short description
- Publisher
- Author

## Todos:
- [x] Created component and unit tests.
- [x] Made sure unit tests pass.
- [x] Added comments where necessary.

## Implementation Decisions

A couple of unit tests have been added to test the CardText component, and the CRA-provided default test for App marked as skipped as it no longer passes and is not needed just yet.

Note that the styles that add an outline around the component and width are there just to demonstrate the component within the app and should be removed before the merge.

I have also changed the comment line in App.tsx from an HTML comment to {/* */} as the former produces a TypeScript error and doesn't let the test suite run.

Resolves #64.

2020-10-26 16:50 UTC, kkyeboah approved these changes, later dismissed
This looks really good 👍. Thanks for including a test and for your contribution.

Please revert your changes to `App.tsx` and we'll be happy to re-approve and merge.

2020-10-26 16:50 UTC, kkyeboah commented on src/components/CardText/CardText.test.tsx
> +import React from "react";
nice 👌

2020-10-26 23:10 UTC, nina-py commented on src/components/CardText/CardText.test.tsx
> +import React from "react";
Thank you Kelvin!

2020-10-26 23:12 UTC, nina-py commented
> Please revert your changes to `App.tsx` and we'll be happy to re-approve and merge.

All done @kkyeboah , please have a look when you have time.

2020-10-27 15:54 UTC, kkyeboah requested changes
Please make sure `App.tsx` is not part of the files changed for this PR.

2020-10-27 23:06 UTC, nina-py commented
Thanks @kkyeboah , App.tsx is now gone from the list of changed files.

2020-10-28 16:21 UTC, kkyeboah approved these changes

2020-10-28 16:21 UTC, merged